// Type declarations for prismjs language component files
declare module "prismjs/components/prism-markup.js" {}
declare module "prismjs/components/prism-markup-templating.js" {}
declare module "prismjs/components/prism-css.js" {}
declare module "prismjs/components/prism-javascript.js" {}
declare module "prismjs/components/prism-typescript.js" {}
declare module "prismjs/components/prism-python.js" {}
declare module "prismjs/components/prism-java.js" {}
declare module "prismjs/components/prism-c.js" {}
declare module "prismjs/components/prism-cpp.js" {}
declare module "prismjs/components/prism-csharp.js" {}
declare module "prismjs/components/prism-go.js" {}
declare module "prismjs/components/prism-rust.js" {}
declare module "prismjs/components/prism-sql.js" {}
declare module "prismjs/components/prism-bash.js" {}
declare module "prismjs/components/prism-scss.js" {}
declare module "prismjs/components/prism-yaml.js" {}
declare module "prismjs/components/prism-graphql.js" {}
declare module "prismjs/components/prism-docker.js" {}
declare module "prismjs/components/prism-swift.js" {}
declare module "prismjs/components/prism-markdown.js" {}
